# Generated by Django 3.1.7 on 2021-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
