# Generated by Django 3.1.7 on 2021-02-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_user_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.user')),
            ],
        ),
    ]
