# Generated by Django 3.1.7 on 2021-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(null=True, to='language.User'),
        ),
    ]
