# Generated by Django 3.1.7 on 2021-02-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20210227_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='text',
        ),
        migrations.CreateModel(
            name='Group_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.group')),
            ],
        ),
    ]
