# Generated by Django 3.1.7 on 2021-02-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0007_auto_20210227_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Language_learn',
            new_name='language_learn',
        ),
    ]
